# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vplan.ui'
#
# Created: Sun Sep 11 17:16:19 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_VPlanClient(object):
    def setupUi(self, VPlanClient):
        VPlanClient.setObjectName(_fromUtf8("VPlanClient"))
        VPlanClient.resize(860, 598)
        VPlanClient.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        VPlanClient.setWindowTitle(QtGui.QApplication.translate("VPlanClient", "FLS Vertretungsplaner", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../vplan/fls_logo.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VPlanClient.setWindowIcon(icon)
        VPlanClient.setStyleSheet(_fromUtf8(""))
        VPlanClient.setAnimated(False)
        self.centralwidget = QtGui.QWidget(VPlanClient)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.vplantable = QtGui.QTableWidget(self.centralwidget)
        self.vplantable.setGeometry(QtCore.QRect(0, 30, 861, 571))
        self.vplantable.setFrameShape(QtGui.QFrame.NoFrame)
        self.vplantable.setFrameShadow(QtGui.QFrame.Sunken)
        self.vplantable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vplantable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.vplantable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.vplantable.setTabKeyNavigation(False)
        self.vplantable.setProperty("showDropIndicator", False)
        self.vplantable.setDragDropOverwriteMode(False)
        self.vplantable.setAlternatingRowColors(True)
        self.vplantable.setShowGrid(True)
        self.vplantable.setGridStyle(QtCore.Qt.DotLine)
        self.vplantable.setCornerButtonEnabled(False)
        self.vplantable.setObjectName(_fromUtf8("vplantable"))
        self.vplantable.setColumnCount(7)
        self.vplantable.setRowCount(7)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "12/1", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "12/1-Data", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "12/1-Data", None, QtGui.QApplication.UnicodeUTF8))
        item.setBackground(QtGui.QColor(183, 186, 248))
        self.vplantable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "13/1", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "13/1-Data", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "13/2", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "13/2-Data", None, QtGui.QApplication.UnicodeUTF8))
        item.setBackground(QtGui.QColor(183, 186, 248))
        self.vplantable.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Std", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Lehrer", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Raum", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "VLehrer", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "VRaum", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Merkmal", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Klasse: 12/1", None, QtGui.QApplication.UnicodeUTF8))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.vplantable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "3", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.vplantable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "JACO", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "310", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "TEST", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "A102", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "1", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.vplantable.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "MÜCK", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "A102", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "SCLO", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "110", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Klasse: 13/1", None, QtGui.QApplication.UnicodeUTF8))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.vplantable.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "2", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.vplantable.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "SCLO", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "110", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.vplantable.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.vplantable.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Frei", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Klasse: 13/2", None, QtGui.QApplication.UnicodeUTF8))
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.vplantable.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "7", None, QtGui.QApplication.UnicodeUTF8))
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.vplantable.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "TEST", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "A203", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.vplantable.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.vplantable.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("VPlanClient", "Frei", None, QtGui.QApplication.UnicodeUTF8))
        self.vplantable.setItem(6, 5, item)
        self.vplantable.horizontalHeader().setVisible(True)
        self.vplantable.horizontalHeader().setHighlightSections(False)
        self.vplantable.verticalHeader().setVisible(False)
        self.vplantable.verticalHeader().setHighlightSections(False)
        self.title = QtGui.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.title.setFont(font)
        self.title.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.title.setAutoFillBackground(False)
        self.title.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 126, 166);"))
        self.title.setText(QtGui.QApplication.translate("VPlanClient", "Vertretungsplan", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setObjectName(_fromUtf8("title"))
        self.label_lastupdate = QtGui.QLabel(self.centralwidget)
        self.label_lastupdate.setGeometry(QtCore.QRect(600, 0, 141, 31))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_lastupdate.setFont(font)
        self.label_lastupdate.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 126, 166);"))
        self.label_lastupdate.setText(QtGui.QApplication.translate("VPlanClient", "Letzte Aktualisierung:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_lastupdate.setObjectName(_fromUtf8("label_lastupdate"))
        self.lastupdate = QtGui.QLabel(self.centralwidget)
        self.lastupdate.setGeometry(QtCore.QRect(740, 0, 121, 31))
        self.lastupdate.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 126, 166);"))
        self.lastupdate.setText(QtGui.QApplication.translate("VPlanClient", "09.06.2011 12:13", None, QtGui.QApplication.UnicodeUTF8))
        self.lastupdate.setObjectName(_fromUtf8("lastupdate"))
        self.datetime = QtGui.QLabel(self.centralwidget)
        self.datetime.setGeometry(QtCore.QRect(240, 0, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.datetime.setFont(font)
        self.datetime.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgb(91, 126, 166);"))
        self.datetime.setText(QtGui.QApplication.translate("VPlanClient", "15.11.2011", None, QtGui.QApplication.UnicodeUTF8))
        self.datetime.setAlignment(QtCore.Qt.AlignCenter)
        self.datetime.setObjectName(_fromUtf8("datetime"))
        VPlanClient.setCentralWidget(self.centralwidget)

        self.retranslateUi(VPlanClient)
        QtCore.QMetaObject.connectSlotsByName(VPlanClient)

    def retranslateUi(self, VPlanClient):
        self.vplantable.setSortingEnabled(False)
        item = self.vplantable.verticalHeaderItem(0)
        item = self.vplantable.verticalHeaderItem(1)
        item = self.vplantable.verticalHeaderItem(2)
        item = self.vplantable.verticalHeaderItem(3)
        item = self.vplantable.verticalHeaderItem(4)
        item = self.vplantable.verticalHeaderItem(5)
        item = self.vplantable.verticalHeaderItem(6)
        item = self.vplantable.horizontalHeaderItem(0)
        item = self.vplantable.horizontalHeaderItem(1)
        item = self.vplantable.horizontalHeaderItem(2)
        item = self.vplantable.horizontalHeaderItem(3)
        item = self.vplantable.horizontalHeaderItem(4)
        item = self.vplantable.horizontalHeaderItem(5)
        item = self.vplantable.horizontalHeaderItem(6)
        __sortingEnabled = self.vplantable.isSortingEnabled()
        self.vplantable.setSortingEnabled(False)
        item = self.vplantable.item(0, 0)
        item = self.vplantable.item(1, 0)
        item = self.vplantable.item(1, 1)
        item = self.vplantable.item(1, 2)
        item = self.vplantable.item(1, 3)
        item = self.vplantable.item(1, 4)
        item = self.vplantable.item(2, 0)
        item = self.vplantable.item(2, 1)
        item = self.vplantable.item(2, 2)
        item = self.vplantable.item(2, 3)
        item = self.vplantable.item(2, 4)
        item = self.vplantable.item(3, 0)
        item = self.vplantable.item(4, 0)
        item = self.vplantable.item(4, 1)
        item = self.vplantable.item(4, 2)
        item = self.vplantable.item(4, 5)
        item = self.vplantable.item(5, 0)
        item = self.vplantable.item(6, 0)
        item = self.vplantable.item(6, 1)
        item = self.vplantable.item(6, 2)
        item = self.vplantable.item(6, 5)
        self.vplantable.setSortingEnabled(__sortingEnabled)

